services:
  db:
    image: ankane/pgvector
    container_name: cliniccloud_db
    restart: always
    environment:
      POSTGRES_DB: cliniccloud
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - cliniccloud-net

  adminer:
    image: adminer
    container_name: cliniccloud_adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - cliniccloud-net
      
  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    container_name: cliniccloud_scraper
    restart: always
    depends_on:
      - db
    volumes:
      - ./scraper:/app
    environment:
      - PYTHONPATH=/app
    networks:
      - cliniccloud-net
      
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: cliniccloud_api
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      - PYTHONPATH=/app
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=cliniccloud
      - DB_USER=admin
      - DB_PASSWORD=admin123
      - SEARCH_ENGINE_URL=http://motor_busqueda:8001
      - DATABASE_URL=postgresql://admin:admin123@db:5432/cliniccloud
    networks:
      - cliniccloud-net


  motor_busqueda:
    build:
      context: ./motor_busqueda
      dockerfile: Dockerfile
    container_name: cliniccloud_motor_busqueda
    restart: always
    depends_on:
      - db
    ports:
      - "8001:8001"
    volumes:
      - ./motor_busqueda:/app
    environment:
      - PYTHONPATH=/app
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=cliniccloud
      - DB_USER=admin
      - DB_PASSWORD=admin123
    networks:
      - cliniccloud-net
      
volumes:
  pgdata:

networks:
  cliniccloud-net:
    driver: bridge