version: "3.9"

services:
  db:
    image: ankane/pgvector
    container_name: cliniccloud_db
    restart: always
    environment:
      POSTGRES_DB: cliniccloud
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

    networks:
      - cliniccloud-net

  adminer:
    image: adminer
    container_name: cliniccloud_adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - cliniccloud-net

volumes:
  pgdata:

networks:
  cliniccloud-net:
    driver: bridge